## This configuration was generated by terraform-provider-oci

data oci_objectstorage_namespace export_namespace {
  compartment_id = var.compartment_ocid
}
resource oci_objectstorage_bucket export_ratd_bronze_bucket {
  access_type    = "NoPublicAccess"
  auto_tiering   = "Disabled"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  freeform_tags = {
  }
  #kms_key_id = <<Optional value not found in discovery>>
  metadata = {
  }
  name                  = "ratd_bronze_bucket"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_events_enabled = "true"
  storage_tier          = "Standard"
  versioning            = "Disabled"
}

resource oci_objectstorage_bucket export_ratd_gold_bucket {
  access_type    = "NoPublicAccess"
  auto_tiering   = "Disabled"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  freeform_tags = {
  }
  #kms_key_id = <<Optional value not found in discovery>>
  metadata = {
  }
  name                  = "ratd_gold_bucket"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_events_enabled = "true"
  storage_tier          = "Standard"
  versioning            = "Disabled"
}

resource oci_objectstorage_bucket export_ratd_silver_bucket {
  access_type    = "NoPublicAccess"
  auto_tiering   = "Disabled"
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  freeform_tags = {
  }
  #kms_key_id = <<Optional value not found in discovery>>
  metadata = {
  }
  name                  = "ratd_silver_bucket"
  namespace             = data.oci_objectstorage_namespace.export_namespace.namespace
  object_events_enabled = "true"
  storage_tier          = "Standard"
  versioning            = "Disabled"
}

resource oci_objectstorage_object export_ratd_bronze_bucket_object_1 {
  bucket = "ratd_bronze_bucket"
  #cache_control = <<Optional value not found in discovery>>
  #content = <<Optional value not found in discovery>>
  #content_disposition = <<Optional value not found in discovery>>
  #content_encoding = <<Optional value not found in discovery>>
  #content_language = <<Optional value not found in discovery>>
  content_md5  = "XxNNeZVNUb9JejFvKqMBPg=="
  content_type = "text/csv"
  #delete_all_object_versions = <<Optional value not found in discovery>>
  metadata = {
  }
  namespace = data.oci_objectstorage_namespace.export_namespace.namespace
  object    = "Trade_Data.csv"
  #opc_sse_kms_key_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
  #source_uri_details = <<Optional value not found in discovery>>
  storage_tier = "Standard"
}

