## This configuration was generated by terraform-provider-oci

resource oci_ons_notification_topic export_ratd_email_notify_topic {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  description = "Email notification topic"
  freeform_tags = {
  }
  name = "ratd_email_notify_topic"
}

resource oci_ons_subscription export_subscription_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  delivery_policy = "{\"backoffRetryPolicy\":{\"maxRetryDuration\":7200000,\"policyType\":\"EXPONENTIAL\"}}"
  endpoint        = "dacharya294@gmail.com"
  freeform_tags = {
  }
  protocol = "EMAIL"
  topic_id = oci_ons_notification_topic.export_ratd_email_notify_topic.id
}

